cloudposse/terraform-aws-ecr

- .gitignore
- LICENSE
- README.md
- main.tf
- output.tf
- variables.tf
* Implement the TF module to create `AWS EC2 Container Registry`
* We need this in order to store our images for Docker containers
* Based on https://bitbucket.org/cultivatedops/terraform-module-aws-ecr
* Docker usage https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/
> Implement the module to create `AWS EC2 Container Registry`

- output.tf
* Add `repository_name` output variable
* The `name` of the created ECR repository is used in other Terraform modules to push Docker images to ECR
> Add `repository_name` output variable

- README.md
- output.tf
* Change `role_name` output to use splat syntax
* To prevent this warning
```
Warning: output "role_name": must use splat syntax to access aws_iam_role.default attribute "name", 
because it has "count" set; 
use aws_iam_role.default.*.name to obtain a list of the attributes across all instances
```
> Change `role_name` output

- README.md
- main.tf
- variables.tf
* Define an `aws_ecr_lifecycle_policy` to expunge old images
* This is a draft version that solves the issue [https://github.com/cloudposse/jenkins/issues/8](https://github.com/cloudposse/jenkins/issues/8).
I do not know your coding patterns, I assumed only untagged for now. However, you can add a ternary to select between tagged/untagged. 
Cheers!
> Added lifecycle policy

- README.md
- main.tf
* Changed `resources` of `aws_iam_policy_document` to wildcard
* To prevent data races (https://github.com/cloudposse/terraform-aws-ecr/issues/8) due to circular dependencies
> Fix Circular Dependency with `aws_iam_policy_document`

- README.md
- README.yaml
* Rename module reference to `ecr` to match example
* Example refers to a module called `ecr` and not `kops_ecr`
* I'm guessing this got copy pasted from cloudposse/terraform-aws-kops-ecr :)
> Replace kops-ecr with ecr (this module)

- main.tf
- output.tf
- variables.tf
* Grant permission to access ECR using ECR policy with principal that have access to it. Basically, let ECR describe who can access it, rather than each user/role listing the modules they can access
* To solve IAM limit problem (more scalable strategy and probably the way we should have done it from the get go)
* Variable `roles` replaced with `principals_full_access` or `principals_readonly_access` and expects list or role\user arns as value
* We removed policies that provide access to the registry. (`policy_login_name`, `policy_login_arn`, `policy_read_name`, `policy_read_arn`, `policy_write_name`, `policy_write_arn`).
So you do not need to attach the policies to IAM role\user. Please provide IAM role\user arn as variable `principals_full_access` or `principals_readonly_access` depend …
> Reinvent permissions to ECR

- main.tf
This passes through the existing tags variable to the ECR resource
so that the repository is tagged with any user requested settings.
Add support for tagging of ECR repositories with user provided metadata
> Add the tags variable to the ECR repository object

- README.md
- main.tf
- versions.tf
Since `null_resource` was dropped in the `terraform-null-label` module starting version [0.15.0](https://github.com/cloudposse/terraform-null-label/releases/tag/0.15.0) and the code was completely removed in the recent version [0.16.0](https://github.com/cloudposse/terraform-null-label/releases/tag/0.16.0), it looks ok to update the `terraform-null-label` to the recent version.
> Update terraform-null-label to v0.16.0

- main.tf
This allows ReadOnly to call DescribeImageScanFindings and FullAccess to call DescribeImageScanFindings & StartImageScan
> Add ImageScan actions to iam roles

- README.md
- docs/terraform.md
- examples/multiple-repo/main.tf
- examples/multiple-repo/outputs.tf
- main.tf
- outputs.tf
- variables.tf
firstly, thanks for great work!
your work helps me lots.
**What:**
I added variables and outputs to create multiple repositories in AWS ECR.
1. passing a list of docker images :
list_image = ["redis", "nginx"]
2. then get a map of image name to the repository :
repository_url_map = {
"redis" = "xxx.dkr.ecr.eu-west-1.amazonaws.com/redis"
"nginx = "xxx.dkr.ecr.eu-west-1.amazonaws.com/nginx "
}
**Why:**
its convenient that if we could create multiple repositories at once by passing a list of docker images as a argument since AWS ECR assuming one repo per one docker image.
> enhancement for multiple repo creation

- README.md
- docs/terraform.md
- main.tf
- variables.tf
* Adds a variable to change tag mutability of images in AWS ECR. 
* Image tag immutability is a useful feature supported by AWS ECR, but there is no way of configuring it using this Terraform module.
* Closes #38
> Add tag mutability setting to the module

- README.md
- README.yaml
- docs/terraform.md
- examples/complete/outputs.tf
- examples/multiple-repo/outputs.tf
- main.tf
- outputs.tf
- variables.tf
* Use `for_each` rather than `count` so that each repo created remains stable as others are added or removed
* Clean up outputs so that they are useful and correctly named
* Revise README to accurately reflect how access permissions are granted. Closes #32.
* Revise list of allowed characters to enable use of ECR "namespaces". Closes #40.
* Previously, adding or removing a repository could cause other repositories to be deleted and recreated, resulting in loss of data 
* Registry ID is just account ID and not a useful output. Repository ARN and URL need to be mapped to Repository name to be useful when creating more than one repository.
> Use for_each to provide stability for named repos

- README.md
- docs/terraform.md
- main.tf
- variables.tf
* Allow protecting images with a given set of tag names
* At Transcend, we tag images with `dev`, `staging`, and `prod` for deployments in addition to their SHA tags. We want to expire images, but not those actively is use.
* https://github.com/aws/containers-roadmap/issues/637
* https://docs.aws.amazon.com/AmazonECR/latest/userguide/lifecycle_policy_examples.html
Note: This change is fully backwards compatible
> Allow protecting images with specified tags

- README.md
1. Update Version Pinning for Terraform to support 0.13
1. This is a relatively minor update that the CloudPosse module already likely supports.
1. This allows module consumers to not individually update our Terraform module to support Terraform 0.13.
> [AUTOMATED] Update Version Pinning for Terraform to support 0.13

- README.md
- main.tf
Signed-off-by: David Karlsen <david@davidkarlsen.com>
* Upgrade terraform-null-label to TF 0.13 compat version
* Support TF 0.13
* #51
> TF13: Need v0.17.0 of terraform-null-label

- README.md
- examples/multiple-repo/main.tf
Looks like in [MR-41](https://github.com/cloudposse/terraform-aws-ecr/pull/41) we added a broken exapmle for deploying ecr with multiple repos. Also the test does not seem to cover this example. Do we want to test this example?
> Use correct variable for multiple images

- main.tf
- Update read-only access to include 
- `ecr:GetLifecyclePolicy`
- `ecr:GetLifecyclePolicyPreview`
-  `ecr:ListTagsForResource`
- Update full access to `ecr:*`
- New features (and corresponding actions) have been added, such as Lifecycle and Image Scan policies.
> Update IAM action lists

- main.tf
- Remove `ecr:GetAuthorizationToken` from read-only access
- This module has included `ecr:GetAuthorizationToken` for years, but today AWS is rejecting it in the Repository Policy, saying "Invalid repository policy provided"
> Remove ecr:GetAuthorizationToken from read-only access

- README.md
- docs/terraform.md
- examples/complete/versions.tf
- main.tf
- versions.tf
* Replace deprecated parameters in aws v4
* Make module compatible with v4
* Closes https://github.com/cloudposse/terraform-aws-ecr/issues/91
> Fix aws provider v4 warnings

- README.md
- docs/terraform.md
- main.tf
* Clean up of the logic surrounding the `var.principals_lambda` policies
* When this was originally implemented it was copy / pastad across multiple policy docs, which isn't necessary and creates a bunch of bloat. 
* Discovered in #98 
* Originally introduced in #88
> fix: cleans up principals lambda logic to separate policy doc

- .github/renovate.json
- .github/workflows/release-branch.yml
- .github/workflows/release-published.yml
- README.md
- docs/terraform.md
- main.tf
- variables.tf
* Add the ability to have organizations as trustees (read-only) for the ECR repository
* As described in #82 , it's sometimes useful to allow an entire organization to consume images from a centralized repository
* closes #82
> feat: add organizations as readonly access

- README.md
- docs/terraform.md
- main.tf
- variables.tf
Add a principal list (`principals_pull_though_access`) which are allowed to use specific repositories as pull through cache (import images from upstream). This holds for repositories where one of the strings in `prefixes_pull_through_repositories` is a prefix of the repository name.
We are using `ecr-public` pull through cache and we want also new images to be downloaded automatically to the cache. Allowed principals for respective repos can use it with the newly introduced variables.
> Allow cache though enabled repositories to fetch image from upstream

- main.tf
- variables.tf
- the change allows to pass wildcards in protected_tags list
- there are use cases when the protected tags are not only prefix defineable and only wildcard can be used like "*prod" or semversion `*.*.*`
- fixes #133
> fix(#133): have ability to use wildcards in protected_tags variale
